project:
  type: website

website:
  title: "Voces del Archivo"
  site-url: "https://vocesdelarchivo.cl"
  page-footer:
    center: |
      ::: {.footer-financiamiento}
      ![](/assets/images/logo-serpat.png){.footer-logo fig-alt="Logo del Servicio Nacional del Patrimonio Cultural"}

      Proyecto financiado por el Fondo del Patrimonio Cultural, Convocatoria 2025, Servicio Nacional del Patrimonio Cultural
      :::

format:
  html:
    css:
      - assets/css/variables.css
      - assets/css/style.css
      - assets/css/fonts.css
