project:
  type: website
  resources:
    - assets/fonts

website:
  title: "Voces del Archivo"
  site-url: "https://vocesdelarchivo.cl"
  page-footer:
    center: |
      ::: {.footer-financiamiento}
      ![](/assets/images/logo-serpat.png){.footer-logo fig-alt="Logo del Servicio Nacional del Patrimonio Cultural"}

      Proyecto financiado por el Fondo del Patrimonio Cultural, Convocatoria 2025, Servicio Nacional del Patrimonio Cultural
      :::

format:
  html:
    theme:
      - default
      - assets/css/custom.scss
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
